## Different ways to sample from two or more `torch.utils.data.Dataset` subclasses

### Method 1. Using `torch.utils.data.ConcatDataset`

In [4]:
import torch
from torch.utils.data import TensorDataset, ConcatDataset
from torch.utils.data import DataLoader

In [5]:
datasets = []
for i in range(3):
    datasets += TensorDataset(torch.arange(i * 10, (i + 1) * 10))
    
dataset = ConcatDataset(datasets)

In [8]:
loader = DataLoader(
    dataset,
    shuffle=True,
    num_workers=0,
    batch_size=5
)

In [9]:
for data in loader:
    print(data, end= '\n\n')

tensor([19, 25, 29, 17, 20])

tensor([ 2, 14, 18,  0,  7])

tensor([ 1, 24, 10, 22, 23])

tensor([ 8,  3, 11, 28,  5])

tensor([21,  6, 27, 12, 15])

tensor([26, 13,  9, 16,  4])



### Method 2. Using `try/except`